
[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = false
startup_mode="Maximized"
# opacity=0.9

[window.padding]
x = 4
y = 4 

[font]
size = 10

[font.normal]
family="JetBrainsMonoNL Nerd Font"

[general]

# themes - alabaster_dark, carbonfox, github_dark_tritanopia.toml 

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]
